#!/usr/bin/env bash
# Kelvin config generation
# Takes the collected installer answers and writes the ~/.kelvin/ directory.
# Sourced by simple.sh and advanced.sh — do not execute directly.

# ── Disko helpers ─────────────────────────────────────────────────────────────

# Write a disko config for the INSTALLER to use (hardcodes disk path).
# $1 = output path for the file
# $2 = disk device (e.g. /dev/nvme0n1)
# $3 = filesystem (btrfs | ext4 | xfs)
# $4 = compression (true | false)  -- only relevant for btrfs
_write_installer_disko_nix() {
  local out="$1"
  local disk="$2"
  local filesystem="${3:-btrfs}"
  local compression="${4:-true}"

  # Build the compress mount option string
  local compress_opt=""
  [[ "$compression" == "true" && "$filesystem" == "btrfs" ]] && \
    compress_opt=' "compress=zstd"'

  # Build root content based on filesystem choice
  local root_content
  if [[ "$filesystem" == "btrfs" ]]; then
    root_content='type      = "btrfs";
              extraArgs = [ "-L" "nixos" "-f" ];
              subvolumes = {
                "@"          = { mountpoint = "/";          mountOptions = [ "subvol=@"         "noatime"'"$compress_opt"' ]; };
                "@home"      = { mountpoint = "/home";      mountOptions = [ "subvol=@home"     "noatime"'"$compress_opt"' ]; };
                "@nix"       = { mountpoint = "/nix";       mountOptions = [ "subvol=@nix"      "noatime"'"$compress_opt"' ]; };
                "@snapshots" = { mountpoint = "/.snapshots"; mountOptions = [ "subvol=@snapshots" "noatime" ]; };
              };'
  elif [[ "$filesystem" == "ext4" ]]; then
    root_content='type       = "filesystem";
              format     = "ext4";
              mountpoint = "/";'
  else
    root_content='type       = "filesystem";
              format     = "xfs";
              mountpoint = "/";'
  fi

  cat > "$out" <<DEOF
# Generated by Kelvin installer — do not edit.
{ ... }:
{
  disko.devices = {
    disk.main = {
      device = "${disk}";
      type   = "disk";
      content = {
        type = "gpt";
        partitions = {
          ESP = {
            size    = "512M";
            type    = "EF00";
            content = {
              type         = "filesystem";
              format       = "vfat";
              mountpoint   = "/boot";
              mountOptions = [ "umask=0077" ];
            };
          };
          root = {
            size    = "100%";
            content = {
              ${root_content}
            };
          };
        };
      };
    };
  };
}
DEOF
}

partition_disk_simple() {
  local disk="$1"
  _write_installer_disko_nix /tmp/kelvin-disko.nix "$disk" btrfs true
  disko --mode destroy,format,mount --yes-wipe-all-disks /tmp/kelvin-disko.nix
}

partition_disk_advanced() {
  local disk="$1"
  local filesystem="${2:-btrfs}"
  # $3 swap, $4 swap_size (handled by NixOS config, not partitioning)
  local compression="${5:-yes}"
  [[ "$compression" == "yes" ]] && compression="true" || compression="false"
  _write_installer_disko_nix /tmp/kelvin-disko.nix "$disk" "$filesystem" "$compression"
  disko --mode destroy,format,mount --yes-wipe-all-disks /tmp/kelvin-disko.nix
}

# ── Config generation — Simple mode ──────────────────────────────────────────

generate_kelvin_config_simple() {
  local kelvin_dir="/mnt/home/${S_USERNAME}/.kelvin"
  mkdir -p "$kelvin_dir"

  # Map selected use cases to option flags
  local dev="false" gaming="false" office="false" media="false" creative="false"
  local science="false" privacy="false" server="false"

  echo "$S_USECASES" | while IFS= read -r line; do
    case "$line" in
      "Development"*) echo "development" ;;
      "Gaming"*)      echo "gaming" ;;
      "Office"*)      echo "office" ;;
      "Media"*)       echo "media" ;;
      "Creative"*)    echo "creative" ;;
      "Science"*)     echo "science" ;;
      "Privacy"*)     echo "privacy" ;;
      "Server"*)      echo "server" ;;
    esac
  done > /tmp/kelvin_usecases

  [[ $(grep -c "development" /tmp/kelvin_usecases) -gt 0 ]] && dev="true"
  [[ $(grep -c "gaming"      /tmp/kelvin_usecases) -gt 0 ]] && gaming="true"
  [[ $(grep -c "office"      /tmp/kelvin_usecases) -gt 0 ]] && office="true"
  [[ $(grep -c "media"       /tmp/kelvin_usecases) -gt 0 ]] && media="true"
  [[ $(grep -c "creative"    /tmp/kelvin_usecases) -gt 0 ]] && creative="true"
  [[ $(grep -c "science"     /tmp/kelvin_usecases) -gt 0 ]] && science="true"
  [[ $(grep -c "privacy"     /tmp/kelvin_usecases) -gt 0 ]] && privacy="true"
  [[ $(grep -c "server"      /tmp/kelvin_usecases) -gt 0 ]] && server="true"

  _write_settings_nix "$kelvin_dir" \
    "${S_HOSTNAME:-kelvin-pc}" \
    "$S_USERNAME" \
    "$S_FULL_NAME" \
    "$S_EMAIL" \
    "$S_TIMEZONE" \
    "en_US.UTF-8" \
    "$S_KEYBOARD" \
    "$S_DISK" \
    "auto" "auto" "x86_64" \
    "limine" "dark" "2" \
    "btrfs" "true" "zram" "0" \
    "unstable" "zen" \
    "$dev" "$gaming" "false" "$office" "$media" "$creative" "$science" "$privacy" "$server" "false" "false" "false" \
    "papirus-dark" "inter" "orchis-dark" \
    "true" "true" "true" "$dev" "false" "false" "false" "true"

  _write_flake_nix "$kelvin_dir"
  _copy_kelvin_modules "$kelvin_dir"
  _write_hardware_config "$kelvin_dir"

  # Lock the flake LAST, once every file is in place. This must be the final
  # write into the directory before nixos-install runs (see _write_flake_lock).
  _write_flake_lock "$kelvin_dir"

  # Permissions
  chown -R "${S_USERNAME}:users" "$kelvin_dir" 2>/dev/null || true
}

# ── Config generation — Advanced mode ────────────────────────────────────────

generate_kelvin_config_advanced() {
  local kelvin_dir="/mnt/home/${A_USERNAME}/.kelvin"
  mkdir -p "$kelvin_dir"

  # Parse use cases
  local dev="false" gaming="false" gaming_tweaks="false" office="false"
  local media="false" creative="false" science="false" privacy="false"
  local server="false" legacy="false" virt="false" security_tools="false"

  echo "$A_USECASES" | while IFS= read -r line; do
    case "$line" in
      "Development"*)    echo "development" ;;
      "Gaming Tweaks"*)  echo "gamingTweaks" ;;
      "Gaming"*)         echo "gaming" ;;
      "Office"*)         echo "office" ;;
      "Media"*)          echo "media" ;;
      "Creative"*)       echo "creative" ;;
      "Science"*)        echo "science" ;;
      "Privacy"*)        echo "privacy" ;;
      "Server"*)         echo "server" ;;
      "Legacy"*)         echo "legacyHardware" ;;
      "Virtualization"*) echo "virtualization" ;;
      "Security"*)       echo "security" ;;
    esac
  done > /tmp/kelvin_usecases_adv

  [[ $(grep -c "development"   /tmp/kelvin_usecases_adv) -gt 0 ]] && dev="true"
  [[ $(grep -c "gaming$"       /tmp/kelvin_usecases_adv) -gt 0 ]] && gaming="true"
  [[ $(grep -c "gamingTweaks"  /tmp/kelvin_usecases_adv) -gt 0 ]] && gaming_tweaks="true"
  [[ $(grep -c "office"        /tmp/kelvin_usecases_adv) -gt 0 ]] && office="true"
  [[ $(grep -c "media"         /tmp/kelvin_usecases_adv) -gt 0 ]] && media="true"
  [[ $(grep -c "creative"      /tmp/kelvin_usecases_adv) -gt 0 ]] && creative="true"
  [[ $(grep -c "science"       /tmp/kelvin_usecases_adv) -gt 0 ]] && science="true"
  [[ $(grep -c "privacy"       /tmp/kelvin_usecases_adv) -gt 0 ]] && privacy="true"
  [[ $(grep -c "server"        /tmp/kelvin_usecases_adv) -gt 0 ]] && server="true"
  [[ $(grep -c "legacyHardware" /tmp/kelvin_usecases_adv) -gt 0 ]] && legacy="true"
  [[ $(grep -c "virtualization" /tmp/kelvin_usecases_adv) -gt 0 ]] && virt="true"
  [[ $(grep -c "security"      /tmp/kelvin_usecases_adv) -gt 0 ]] && security_tools="true"

  # Parse services
  local ssh="false" cups="false" bluetooth="false" docker="false"
  local tailscale="false" syncthing="false" fail2ban="false"
  local ananicy="${A_ANANICY:-yes}"
  [[ "$ananicy" == "yes" ]] && ananicy="true" || ananicy="false"

  echo "$A_SERVICES" | grep -qi "SSH"           && ssh="true"
  echo "$A_SERVICES" | grep -qi "CUPS"          && cups="true"
  echo "$A_SERVICES" | grep -qi "Bluetooth"     && bluetooth="true"
  echo "$A_SERVICES" | grep -qi "Docker"        && docker="true"
  echo "$A_SERVICES" | grep -qi "Tailscale"     && tailscale="true"
  echo "$A_SERVICES" | grep -qi "Syncthing"     && syncthing="true"
  echo "$A_SERVICES" | grep -qi "fail2ban"      && fail2ban="true"
  [[ "$dev" == "true" ]] && docker="true"

  local compression="true"
  [[ "$A_COMPRESSION" == "no" ]] && compression="false"

  _write_settings_nix "$kelvin_dir" \
    "$A_HOSTNAME" "$A_USERNAME" "$A_FULL_NAME" "$A_EMAIL" \
    "$A_TIMEZONE" "en_US.UTF-8" "$A_KEYBOARD" "$A_DISK" \
    "$A_GPU" "$A_CPU" "$A_ARCH" \
    "$A_BOOTLOADER" "$A_BOOT_THEME" "2" \
    "$A_FILESYSTEM" "$compression" "$A_SWAP" "${A_SWAP_SIZE:-0}" \
    "$A_CHANNEL" "$A_KERNEL" \
    "$dev" "$gaming" "$gaming_tweaks" "$office" "$media" "$creative" "$science" "$privacy" "$server" "$legacy" "$virt" "$security_tools" \
    "$A_ICON_PACK" "$A_FONT" "$A_COLOR_SCHEME" \
    "$ssh" "$cups" "$bluetooth" "$docker" "$tailscale" "$syncthing" "$fail2ban" "$ananicy"

  _write_flake_nix "$kelvin_dir"
  _copy_kelvin_modules "$kelvin_dir"
  _write_hardware_config "$kelvin_dir"

  # Lock the flake LAST, once every file is in place. This must be the final
  # write into the directory before nixos-install runs (see _write_flake_lock).
  _write_flake_lock "$kelvin_dir"

  chown -R "${A_USERNAME}:users" "$kelvin_dir" 2>/dev/null || true
}

# ── settings.nix writer ───────────────────────────────────────────────────────
#
# Writes the user's chosen VALUES (kelvin.* = ...). The option *declarations*
# (options.kelvin = mkOption ...) live in the repo's options.nix, which is baked
# onto the ISO and copied into ~/.kelvin alongside this file. Both are imported
# by the generated flake. Keeping values in a separate file means this writer
# must never clobber the declarations module — hence settings.nix, not
# options.nix. Without the declarations module present, config.kelvin does not
# exist and evaluation fails with "attribute 'kelvin' missing".
_write_settings_nix() {
  local dir="$1"
  local hostname="$2"   username="$3"   fullname="$4"    email="$5"
  local timezone="$6"   locale="$7"     keyboard="$8"    disk="$9"
  local gpu="${10}"      cpu="${11}"     arch="${12}"
  local bootloader="${13}" boot_theme="${14}" generations="${15}"
  local filesystem="${16}" zstd="${17}"  swap="${18}"      swap_size="${19}"
  local channel="${20}"    kernel="${21}"
  local uc_dev="${22}"     uc_gaming="${23}"  uc_gaming_tweaks="${24}"
  local uc_office="${25}"  uc_media="${26}"   uc_creative="${27}"
  local uc_science="${28}" uc_privacy="${29}" uc_server="${30}"
  local uc_legacy="${31}"  uc_virt="${32}"    uc_security="${33}"
  local icon_pack="${34}"  font="${35}"       color_scheme="${36}"
  local svc_ssh="${37}"    svc_cups="${38}"   svc_bt="${39}"
  local svc_docker="${40}" svc_ts="${41}"     svc_sync="${42}"
  local svc_f2b="${43}"    svc_ananicy="${44}"

  cat > "${dir}/settings.nix" <<OPTEOF
# ~/.kelvin/settings.nix
# Generated by the Kelvin installer. Edit freely.
# Apply changes: kelvin update  (or sudo nixos-rebuild switch --flake ~/.kelvin/#kelvin)
{
  kelvin = {
    # Identity
    hostname       = "${hostname}";
    username       = "${username}";
    fullName       = "${fullname}";
    email          = "${email}";
    timezone       = "${timezone}";
    locale         = "${locale}";
    keyboardLayout = "${keyboard}";
    disk           = "${disk}";

    # Hardware
    gpu  = "${gpu}";
    cpu  = "${cpu}";
    arch = "${arch}";

    # Bootloader
    bootloader = {
      type        = "${bootloader}";
      theme       = "${boot_theme}";
      generations = ${generations};
    };

    # Filesystem
    filesystem      = "${filesystem}";
    zstdCompression = ${zstd};
    swap            = "${swap}";
    swapSize        = ${swap_size};

    # Channel + Kernel
    channel = "${channel}";
    kernel  = "${kernel}";

    # Use cases
    useCases = {
      development    = ${uc_dev};
      gaming         = ${uc_gaming};
      gamingTweaks   = ${uc_gaming_tweaks};
      office         = ${uc_office};
      media          = ${uc_media};
      creative       = ${uc_creative};
      science        = ${uc_science};
      privacy        = ${uc_privacy};
      server         = ${uc_server};
      legacyHardware = ${uc_legacy};
      virtualization = ${uc_virt};
      security       = ${uc_security};
    };

    # Desktop
    desktop = {
      iconPack    = "${icon_pack}";
      font        = "${font}";
      colorScheme = "${color_scheme}";
    };

    # Services
    services = {
      ssh        = ${svc_ssh};
      cups       = ${svc_cups};
      bluetooth  = ${svc_bt};
      docker     = ${svc_docker};
      tailscale  = ${svc_ts};
      syncthing  = ${svc_sync};
      fail2ban   = ${svc_f2b};
      ananicy    = ${svc_ananicy};
    };
  };
}
OPTEOF
}

# ── flake.nix writer ──────────────────────────────────────────────────────────

_write_flake_nix() {
  local dir="$1"

  cat > "${dir}/flake.nix" <<'FLKEOF'
{
  description = "Kelvin — my personal NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    plasma-manager = {
      url = "github:nix-community/plasma-manager";
      inputs.nixpkgs.follows   = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };
  };

  outputs = { self, nixpkgs, home-manager, disko, plasma-manager, ... }: {
    nixosConfigurations.kelvin = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ./options.nix    # option declarations (options.kelvin = mkOption ...)
        ./settings.nix   # user values (kelvin.* = ...), written by the installer
        ./configuration.nix
        ./disko.nix
        home-manager.nixosModules.home-manager
        disko.nixosModules.disko
        { home-manager.sharedModules = [ plasma-manager.homeModules.plasma-manager ]; }
      ];
    };
  };
}
FLKEOF
}

# ── flake.lock writer ─────────────────────────────────────────────────────────
#
# Why this exists:
#   ~/.kelvin is a *non-git, writable* path flake. When `nixos-install --flake`
#   evaluates such a flake and finds no flake.lock, nix locks the inputs and
#   then writes flake.lock back INTO the directory mid-evaluation. That write
#   changes the directory's contents after nix has already computed and cached
#   its NAR hash, producing:
#
#     error: NAR hash mismatch in input 'path:/mnt/home/<user>/.kelvin?...'
#
#   By generating a complete flake.lock here — as the final write into the
#   directory, after every other file is in place and before nixos-install runs
#   — the lock already exists and is complete, so nixos-install reads it and
#   never modifies the tree. The NAR hash stays stable across evaluation.
#
# This is intentionally the LAST thing written to $dir. Nothing else may write
# into the directory after this point until nixos-install has finished.
_write_flake_lock() {
  local dir="$1"
  # Pre-fetch and pin all inputs. Flakes are enabled in the live ISO, but pass
  # the flags explicitly so this works regardless of nix.conf state. This also
  # warms the store, which speeds up the subsequent nixos-install.
  nix --extra-experimental-features "nix-command flakes" \
    flake lock "$dir"
}

# ── Copy module tree ──────────────────────────────────────────────────────────

_copy_kelvin_modules() {
  local dir="$1"
  local kelvin_source

  # Find where the Kelvin repo lives on the ISO
  if [[ -d /etc/kelvin ]]; then
    kelvin_source="/etc/kelvin"
  elif [[ -d /etc/kelvin-installer ]]; then
    kelvin_source="/etc/kelvin-installer"
  else
    echo "WARNING: Could not find Kelvin source modules. Skipping copy." >&2
    return 0
  fi

  # IMPORTANT: dereference symlinks while copying (-L). On the live ISO the
  # source lives under /etc/kelvin, where each entry is an environment.etc
  # symlink into /etc/static/kelvin/... -> the read-only Nix store. A plain
  # `cp -r` of such a symlinked *directory* preserves the top-level entry as an
  # absolute symlink (e.g. ~/.kelvin/hardware -> /etc/static/kelvin/hardware).
  # The generated flake then resolves ./hardware/generated.nix through that link
  # to an absolute path and nixos-install fails under pure evaluation with:
  #   error: access to absolute path '/etc/static/kelvin/hardware/generated.nix'
  #          is forbidden in pure evaluation mode
  # `-L` copies the real files instead, so ~/.kelvin is self-contained and every
  # import stays relative. (It also unblocks the hardware/generated.nix overwrite
  # below, which otherwise would write through a symlink into the read-only store.)
  for subdir in system hardware desktop home assets; do
    [[ -d "${kelvin_source}/${subdir}" ]] && \
      cp -rL "${kelvin_source}/${subdir}" "${dir}/"
  done

  # options.nix here is the option DECLARATIONS module (options.kelvin = mkOption
  # ...). It is what makes config.kelvin exist; the installer writes the matching
  # values into settings.nix separately, so this copy must not be confused with
  # that. Without options.nix in ~/.kelvin, nixos-install fails with
  # "attribute 'kelvin' missing".
  for f in configuration.nix options.nix packages.nix user-packages.nix disko.nix; do
    [[ -f "${kelvin_source}/${f}" ]] && \
      cp -L "${kelvin_source}/${f}" "${dir}/"
  done

  # Store-sourced copies inherit read-only (0444) permissions. Make the tree
  # writable so _write_hardware_config can overwrite generated.nix and so the
  # user can edit ~/.kelvin later (`kelvin update`).
  chmod -R u+w "$dir"

  # Ensure user-packages.nix exists even if copy failed
  if [[ ! -f "${dir}/user-packages.nix" ]]; then
    cat > "${dir}/user-packages.nix" <<'UPEOF'
# Packages installed via kelvin-store. Edit with: kelvin-store
{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    # KELVIN-STORE-BEGIN
    # KELVIN-STORE-END
  ];
}
UPEOF
  fi
}

# ── Hardware config ───────────────────────────────────────────────────────────

_write_hardware_config() {
  local dir="$1"
  local generated="/mnt/etc/nixos/hardware-configuration.nix"

  # The installer runs `nixos-generate-config --no-filesystems --root /mnt`
  # before this, so $generated carries hardware detection (kernel modules, CPU
  # microcode hints, imports) but NO fileSystems/swapDevices — those belong to
  # disko alone. We just relocate it under the flake as hardware/generated.nix.
  if [[ -f "$generated" ]]; then
    mkdir -p "${dir}/hardware"
    cp "$generated" "${dir}/hardware/generated.nix"
  else
    echo "WARNING: hardware-configuration.nix not found at ${generated}" >&2
    echo "Run nixos-generate-config --no-filesystems --root /mnt and copy the result to ${dir}/hardware/generated.nix" >&2
  fi
}
