# This file is generated by nixos-generate-config during Kelvin installation.
# It contains hardware-specific configuration discovered from the target machine
# (kernel modules, filesystem UUIDs, CPU features, etc.).
#
# The Kelvin installer runs:
#   nixos-generate-config --root /mnt
# and copies the output to ~/.kelvin/hardware/generated.nix
#
# DO NOT hand-edit this file — re-run nixos-generate-config if hardware changes.

{ ... }: {}
